[package]
name = "gitignore-builder-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
clap = { version = "4.4.6", features = ["derive"] }
reqwest = "0.11.22"
shuttle-axum = "0.29.0"
shuttle-runtime = "0.29.0"
tokio = "1.33.0"

[[bin]]
name="cli"
path="src/bin/cli.rs"

[[bin]]
name="server"
path="src/bin/server.rs"

[[bin]]
name="gitignore-builder-rs"
path="src/bin/shuttle.rs"
